#!/bin/bash
#

# Script to install check_mk
#
# Version 1.3
#
# 2012-10-12 FLX f@qsol.ro
#	- Get agent and plunig from GitHub
#	- Added support (experimental) for Debian
#
# 2012-10-04 FLX f@qsol.ro
#	- Modified to be run on target machine
#
# 2012-09-27 FLX f@qsol.ro
#	- Modified to be run on target machine
#
# 2012-09-13 FLX f@qsol.ro
#	- First draft
#


#####################################################################
#
#	Global Configure section
#
#####################################################################

#http://mathias-kettner.de/download/check_mk-agent-1.2.0p3-1.noarch.rpm
mk_site='http://mathias-kettner.de/download'

mk_agent_rpm='check_mk-agent-1.2.0p3-1.noarch.rpm'
mk_agent_deb='check-mk-agent_1.2.0p3-2_all.deb'



#monitor_site='monitor.qsol.ro'

# Needed for iptables
monitor_ip='89.238.194.86'



agent='check_mk_agent'

# mk_apache  mk_exim  mk_mysql  mk_nginx  mk_zmailer
git_repo='https://raw.github.com/felixenescu/check_mk_plugins/master/check_mk_agent'
git_agent='check_mk_agent.linux'
plugins='mk_apache  mk_exim  mk_mysql'
plugins_all='mk_apache  mk_exim  mk_mysql  mk_nginx  mk_zmailer'

working_dir='/root/qsol/check_mk'
agent_install_dir='/usr/bin'
plugin_install_dir='/usr/lib/check_mk_agent/plugins'

#####################################################################


WGET='wget --no-verbose '

#####################################################################

if [ ! -d /root/qsol ]; then
	mkdir /root/qsol
fi
cd /root/qsol

if [ ! -d /root/qsol/check_mk ]; then
	mkdir /root/qsol/check_mk
fi
cd check_mk

crt_dir=`pwd`
if [ "$crt_dir" != "$working_dir" ] ; then
	echo "wrong working dir $crt_dir"
	exit 127
fi

if which yum; then
	echo "Using yum."
	install_cmd='yum install --assumeyes '
	local_install_cmd='yum localinstall --nogpgcheck --assumeyes '
	mk_agent_pkg=$mk_agent_rpm
elif which apt-get; then
	echo "Using apt-get. Debian not really tested - use on your own risk."
	install_cmd='apt-get install '
	local_install_cmd='dpkg --install '
	mk_agent_pkg=$mk_agent_deb
else
	echo "yum or apt-get not found."
	exit 127
fi

if which wget ; then
	echo "wget found."
else
	$install_cmd wget

	if which wget ; then
		echo "wget installation ok."
	else
		echo "wget installation failed."
		exit 127
	fi
fi



if $WGET $mk_site/$mk_agent_pkg; then
	echo "Got check_mk agent"
else 
	echo "wget $mk_site/$mk_agent_pkg failed."
	exit 127
fi

if $install_cmd xinetd; then
	echo "xinetd installation ok."
else
	echo "xinetd installation failed."
	exit 127
fi
 
if $local_install_cmd $mk_agent_pkg; then
	echo "Installed check_mk agent"
else
	echo "Error installing check_mk agent"
	exit 127
fi



# Get our version of check_mk_agent
if $WGET $git_repo/$git_agent; then
	echo "Got QSol check_mk_agent"
	cp $git_agent $agent_install_dir/$agent
	chmod +x $agent_install_dir/$agent
else 
	echo "wget $git_repo/$git_agent failed."
	exit 127
fi

# Get our plugins
for plugin in $plugins; do
	if $WGET $git_repo/$plugin; then
		echo "Got QSol plugin $plugin"
		cp $plugin $plugin_install_dir/
		chmod +x $plugin_install_dir/$plugin
	else 
		echo "wget $git_repo/$plugin failed."
		exit 127
	fi
done

if which apachectl || which apache2ctl || [ -x /usr/local/apache/bin/apachectl ]; then
	echo '<<<apache found>>>'
	
	if $install_cmd lynx ; then
		echo "Installed lynx"
	else
		echo "Error installing lynx"
		exit 127
	fi
fi

if which mysql; then
	echo '<<<mysql found>>>'
	if [ -f "/root/.my.cnf" ] ; then
		echo ".my.cnf already exists"
	else
		echo "[client]" >> /root/.my.cnf
		echo "user=\"USER\"" >> /root/.my.cnf
		echo "password=\"PASSWORD\"" >> /root/.my.cnf
		chmod 0600 /root/.my.cnf
		echo "Template .my.cnf created. Be sure to edit it."
	fi
fi

iptables -I INPUT -s $monitor_ip -p tcp --dport 6556 -j ACCEPT 

exit 0




