#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

fortigate_cpu_default_levels = (80.0, 90.0)

def check_fortigate_cpu(item, params, info):
    warn, crit = params
    current = saveint(info[0][0])
    state = 0
    icon = ''
    if current >= warn:
        state = 1
	icon = "(!)"
    if current >= crit:
        state = 2
	icon = "(!!)"

    perf = [("util", current, warn, crit, 0, 100)]
    return(state, nagios_state_names[state] + " - %2.1f%%%s (levels at %d/%d percent)" % (current, icon, warn, crit), perf)

# For version 4
#1.3.6.1.4.1.12356.101.4.1.3.0
check_info["fortigate_cpu"] = {
    "check_function"        : check_fortigate_cpu,
    "inventory_function"    : lambda info: [(None, "fortigate_cpu_default_levels")],
    "service_description"   : "CPU utilization",
    "has_perfdata"          : True,
    "group"                 : "cpu_utilization",
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.4.1.12356.101.4.1.3.0"),
    "snmp_info"		    : ( ".1.3.6.1.4.1.12356.101.4.1", [ 3 ]),
}

#    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.4.1.12356.1.8.0"),
#    "snmp_info"		    : ( ".1.3.6.1.4.1.12356.1", [ 8 ]),
