#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

fortigate_sessions_default_levels = (100000, 150000)

def check_fortigate_sessions(item, params, info):
    warn, crit = params
    current = saveint(info[0][0])
    state = 0
    icon = ''
    if current >= warn:
        state = 1
	icon = "(!)"
    if current >= crit:
        state = 2
	icon = "(!!)"

    perf = [("session", current, warn, crit)]
    return(state, nagios_state_names[state] + " - %d Session%s (levels at %d/%d)" % (current, icon, warn, crit), perf)

# For version 4
#1.3.6.1.4.1.12356.101.4.1.8.0
check_info["fortigate_sessions"] = {
    "check_function"        : check_fortigate_sessions,
    "inventory_function"    : lambda info: [(None, "fortigate_sessions_default_levels")],
    "service_description"   : "Sessions",
    "has_perfdata"          : True,
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.4.1.12356.101.4.1.8.0"),
    "snmp_info"		    : ( ".1.3.6.1.4.1.12356.101.4.1", [ 8 ]),
}

