#!/bin/bash

# Check_mk plugin to check zmailer 
#
#	Version 1.0
#
# 2012-09-23 FLX f@qsol.ro
#	- First  version
#

if [ -x /opt/zmailer/bin/mailq ]; then
	# Just in case more that one email system is installed on server
	echo '<<<zmailer>>>'
	/opt/zmailer/bin/mailq -M
fi

